---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: UserProvider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: UserProvider
    spec:
      containers:
      - name: UserProvider
        image: fredk8s.azurecr.io/fredtest:0.0.1
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: UserProvider
spec:
  type:  NodePort
  ports:
  - port: 8090
  selector:
    app: UserProvider